### ISSUE TITLE
--skip-commit flag not working properly on versionize 1.8.0

### ISSUE THREAD

**Issue by Alenano360** [saintedlama/versionize#34]
When executing the following command on Azure Pipelines:

`/home/vsts/work/versionize -w "<REPO>/" -r 0.29.0 --skip-dirty --skip-commit -i`

We get the following error:
```
========================== Starting Command Output ===========================
/bin/bash --noprofile --norc /home/vsts/work/_temp/781ef2ad-159b-4e0d-9e82-a2b1bcfc5087.sh
Discovered 1 versionable projects
  * /home/vsts/work/1/s/<REPOSITORY>/CatalogMS/CatalogMS.csproj
√ bumping version from 0.29.0 to 0.29.0 in projects
Unhandled exception. System.InvalidOperationException: Remote url https://<ORG>@dev.azure.com/<ORG>/<PROJ>/_git/<REPO> is not recognized as valid Azure HTTPS pattern
   at Versionize.Changelog.AzureLinkBuilder..ctor(String pushUrl) in C:\p\github\versionize\Versionize\Changelog\AzureLinkBuilder.cs:line 36
   at Versionize.Changelog.LinkBuilderFactory.CreateFor(Repository repository) in C:\p\github\versionize\Versionize\Changelog\LinkBuilderFactory.cs:line 24
   at Versionize.WorkingCopy.Versionize(VersionizeOptions options) in C:\p\github\versionize\Versionize\WorkingCopy.cs:line 96
   at Versionize.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\p\github\versionize\Versionize\Program.cs:line 59
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass146_0.<OnExecute>b__0(CancellationToken _)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Versionize.Program.Main(String[] args) in C:\p\github\versionize\Versionize\Program.cs:line 64
/home/vsts/work/_temp/781ef2ad-159b-4e0d-9e82-a2b1bcfc5087.sh: line 1:  5035 Aborted                 (core dumped) /home/vsts/work/versionize -w "<REPO>/" -r 0.29.0 --skip-dirty --skip-commit -i
```
**NOTE:**
We are getting the same error running versionize locally.

**Comment by lungosta** [comment]
I'm having the same problem
